
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'sectionsCOMMENT EQUAL NEWLINE SECBEGIN SECEND TEXTsections : section\n                |  sections sectionsection : sectionid keywordssectionid : SECBEGIN TEXT SECEND NEWLINEkeywords : keyword\n                | keywords keywordkeyword : NEWLINE\n                | TEXT EQUAL NEWLINE\n                | TEXT EQUAL TEXT NEWLINE'
    
_lr_action_items = {'SECBEGIN':([0,1,2,5,6,7,8,11,15,17,],[4,4,-1,-2,-3,-5,-7,-6,-8,-9,]),'$end':([1,2,5,6,7,8,11,15,17,],[0,-1,-2,-3,-5,-7,-6,-8,-9,]),'NEWLINE':([3,6,7,8,11,12,13,14,15,16,17,],[8,8,-5,-7,-6,15,16,17,-8,-4,-9,]),'TEXT':([3,4,6,7,8,11,12,15,16,17,],[9,10,9,-5,-7,-6,14,-8,-4,-9,]),'EQUAL':([9,],[12,]),'SECEND':([10,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sections':([0,],[1,]),'section':([0,1,],[2,5,]),'sectionid':([0,1,],[3,3,]),'keywords':([3,],[6,]),'keyword':([3,6,],[7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sections","S'",1,None,None,None),
  ('sections -> section','sections',1,'p_sections','parser.py',65),
  ('sections -> sections section','sections',2,'p_sections','parser.py',66),
  ('section -> sectionid keywords','section',2,'p_section','parser.py',69),
  ('sectionid -> SECBEGIN TEXT SECEND NEWLINE','sectionid',4,'p_sectionid','parser.py',72),
  ('keywords -> keyword','keywords',1,'p_keywords','parser.py',75),
  ('keywords -> keywords keyword','keywords',2,'p_keywords','parser.py',76),
  ('keyword -> NEWLINE','keyword',1,'p_keyword','parser.py',79),
  ('keyword -> TEXT EQUAL NEWLINE','keyword',3,'p_keyword','parser.py',80),
  ('keyword -> TEXT EQUAL TEXT NEWLINE','keyword',4,'p_keyword','parser.py',81),
]
